default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rsc-meeting-minutes-dev

test:
  <<: *default
  database: rsc-meeting-minutes-test

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] %>
